// Generated by Selenium IDE
import org.junit.Test;
import org.junit.After;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchtestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchtest() {
    driver.get("http://35.197.147.187/homeCustomerServlet");
    driver.manage().window().setSize(new Dimension(974, 1039));
    driver.findElement(By.name("location")).click();
    {
      WebElement dropdown = driver.findElement(By.name("location"));
      dropdown.findElement(By.xpath("//option[. = 'Đà Nẵng']")).click();
    }
    driver.findElement(By.id("numberInput")).click();
    driver.findElement(By.id("numberInput")).sendKeys("2");
    driver.findElement(By.name("check_in_date")).click();
    driver.findElement(By.name("check_in_date")).sendKeys("2024-07-19");
    driver.findElement(By.name("check_out_date")).click();
    driver.findElement(By.name("check_out_date")).sendKeys("2024-07-20");
    driver.findElement(By.name("number_of_rooms")).click();
    driver.findElement(By.name("number_of_rooms")).sendKeys("1");
    driver.findElement(By.cssSelector(".btn-outline-secondary")).click();
    driver.findElement(By.cssSelector(".card:nth-child(1) .card-body")).click();
    assertThat(driver.findElement(By.cssSelector(".card:nth-child(1) .card-title")).getText(), is("Khách sạn và căn hộ Seashore"));
  }
}
